library(dplyr)
data<-read.table("household_power_consumption.txt",header = TRUE,sep = ";",stringsAsFactors = FALSE)
selected<-filter(data, data$Date == "1/2/2007"|data$Date == "2/2/2007")
DateTime<-paste(selected$Date,selected$Time)
DateTime<-strptime(DateTime, "%d/%m/%Y %H:%M:%S")
selected<-cbind(DateTime,selected)
png("Plot 3.png")
with(selected, plot(DateTime,Sub_metering_1, main = "Sub_Metering",xlab = "Day of week",ylab = "Energy Sub Metering", type = "n"))
lines(selected$DateTime,selected$Sub_metering_1)
lines(selected$DateTime,selected$Sub_metering_2, col = "red")
lines(selected$DateTime,selected$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()